### PR TITLE
fix: 🐛 Japan flag included

### PR DESCRIPTION
**Pull request by Marincor**
Japan flag included; the pattern scss to included the flag does not
work, so I  created a css file into a teams folder created, see if is
worth it!

✅ Closes: #17

### CODE REVIEW

**Comment by laisfrigerio** [comment]
Hey @Marincor Thanks for your contributation!!!

It's not necessary to add .css file into css folder.

To test you code, You must run:

`npm install`

and 

`npm run build`

Last command run you .scss files and generate de .css file into css folder.

And to test this project locally, You can Install Live Server extension from VSCode

Or run

`npx serve`

**Comment by Marincor** [comment]
Css teams folder removed. First time working with scss, sorry 😂. See now. ^^

**Comment by laisfrigerio** [comment]
@Marincor I'll approve your pull request. 

Thanks for you contribution :)

**Comment by laisfrigerio** [comment]
@Marincor  Thanks for your contribution :)

**Pull request merged**
