### PR TITLE
Add iran flag

### PR DESCRIPTION
**Pull request by amirghazi87**

### CODE REVIEW

**Comment by laisfrigerio** [comment]
@amirghazi87 I made a review into your code here.

Sorry for not metion you before

**Comment by amirghazi87** [comment]
> @amirghazi87 I made a review into your code here.
> 
> Sorry for not mention you before

I fix conflict but I can't see the review

**Comment by laisfrigerio** [comment]
@amirghazi87 following the review:

review

**Comment by amirghazi87** [comment]
> @amirghazi87 following the review:
> 
> review

Oh, I'm sorry, i think now is correct ( when i was write that i can't test it , like now )

**Pull request closed without merging**
